platform :ios, '8.0'

use_frameworks!

target 'Nudgespot_Example' do
    pod 'Nudgespot', :path => '../'
    
    pod 'Firebase'
    pod 'FirebaseMessaging'
    
    target 'Nudgespot_Tests' do
        inherit! :search_paths
        
    end
end
