platform :ios, '7.0'

inhibit_all_warnings!

pod 'Reachability'
pod 'AFNetworking'
pod 'Firebase'
pod 'FirebaseMessaging'

target 'Nudgespot_Example' do
    pod 'Nudgespot', :path => '../'
    
    target 'Nudgespot_Tests' do
        inherit! :search_paths
        
    end
end
