source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

inhibit_all_warnings!

pod 'Google/CloudMessaging'
pod 'Reachability'
pod 'AFNetworking'

target 'Nudgespot_Example' do
    pod 'Nudgespot', :path => '../'
    
    target 'Nudgespot_Tests' do
        inherit! :search_paths
        
        
    end
end
